### PR TITLE
Add Tag Command 2

### PR DESCRIPTION
**Pull request by UnwilledTangent**

### CODE REVIEW

**Comment by amoonguss1** [comment]
Lgtm! the pull request adds a good implementation of tag

**Comment by dsja612** [comment]
We have already merged your implementation from your previous pr! 😓 We can close this PR

**Comment by UnwilledTangent** [comment]
Oh sorry, I didn't realise. My bad!

**Comment by UnwilledTangent** [comment]
Sorry guys, I think that this is necessary.

**Pull request merged**
